<!doctype html>
<html lang="en">
	<head>
	    <meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	    <meta http-equiv="X-UA-Compatible" content="ie=edge">
	    <title>Arenella-ICT</title>
	    <style type="text/css">
	    <#include "/styles.css">
	    </style>
	    <#setting number_format="computer">
	</head>
	<body>
		<div style="margin-top: 10px">Dear ${recipientName}</div>
		
		<p>
		We are pleased to inform you that you have received a new reaction from a candidate relating to the followng post on the job board. 
		</p>
		<p><b>${listingName}</b></p>
		<p>You can view the message and download and view any attachments from your personal Arenella-ICT inbox</p>
		<P>
			<a href="https://www.arenella-ict.com">https://www.arenella-ict.com</a>
		</P>
		
		<div> 
			<p>Kind regards</p>
			<p>Kevin</p>
		</div>
		<p class="disclaimer">
			Please be informed messages and attachemnts are sent by unverified sources. 
			We recommend always keeping your anti-virus programs up to date and not no enable macros or dynamic content if 
			prompted to do so when viewing any file on the internet.
		</p>
	</body>
</html>