<!doctype html>
<html lang="en">
	<head>
	    <meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	    <meta http-equiv="X-UA-Compatible" content="ie=edge">
	    <title>Arenella-ICT</title>
	    <style type="text/css">
	    <#include "/styles.css">
	    </style>
	    <#setting number_format="computer">
	</head>
	<body>
		<div style="margin-top: 10px">Dear ${recipientName}</div>
		
		<p>
		You have ${likeCount} new likes and ${replyCount} new replies on Arenella-ICT news feed.
		</p>
		
		<P>
			<a href="https://www.arenella-ict.com/newsfeed/">https://www.arenella-ict.com</a>
		</P>
		
		<div> 
			<p>Kind regards</p>
			<p>Kevin</p>
		</div>
		
	</body>
</html>