<!doctype html>
<html lang="en">
	<head>
	    <meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	    <meta http-equiv="X-UA-Compatible" content="ie=edge">
	    <title>Arenella-ICT</title>
	</head>
	<body>
		<div style="margin-top: 10px">Dear ${firstname}</div>
		
		<p>
		I have set you up with a 90 day free trial account. During the trial period you have full access to all the Arenella-ICT features. At the end of the 90 days the trial will stop 
		automatically. For continued access to the site after the trial expires you can take out a subscription via the site for 120 euro's per year ex tax.
		</p>
	
		<P>
			<a href="https://www.arenella-ict.com">https://www.arenella-ict.com</a>
		</P>
	
		<h3>Your login details are </h3>
	
		<div>
			<table>
				<tr>
					<td><b>Username</b></td>
					<td>${userid}</td>
				</tr>
				<tr>
					<td><b>Password</b></td>
					<td>${password}</td>
				</tr>
			</table>
		</div>
		
		<p>During the trial you will have access to all the features of the site including</p>
		
		<h3>Suggestions</h3>
		<p>This is an advanced search tool. It returns the best matches based upon the combination of filters selected by you</p>
		
		<h3>Job Board</h3>
		<p>You can add your open positions to the Job board. The advert's you place will be actively promoted within a network of 23000+ connections. </p>
		
		<h3>Marketplace</h3>
		<p>The marketplace allows collaboration between recruiters. You can request candidates for positions you are trying to fill and you can also offer candidates that you have available but currently have no suitable role for. </p>
		
		<div> 
			<p>Kind regards</p>
			<p>Kevin</p>
		</div>
		
	</body>
</html>