<!doctype html>
<html lang="en">
	<head>
	    <meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	    <meta http-equiv="X-UA-Compatible" content="ie=edge">
	    <title>Arenella-ICT</title>
	</head>
	<body>
		<div style="margin-top: 10px">Dear ${firstname}</div>
		
		<p>
		You have successfully created a Candidate account with Arenella-ICT. Recruiters will now be able to search on and download your CV so that they can contact you with 
		relevant roles.  
		</p>
		<p>
		Currently you have a basic profile which has been created by scanning your CV and extracting the relevant information. You can also log in to the system to 
		add extra information to your profile. This will provide extra information to the recruiters and increase the chances of being contacted by them. 
		</p>
		<p>
		If you have any queries please feel free to contact me by replying to this email 
		</p>
		<P>
			<a href="https://www.arenella-ict.com">https://www.arenella-ict.com</a>
		</P>
	
		<h3>Your login details are </h3>
	
		<div>
			<table>
				<tr>
					<td><b>Username</b></td>
					<td>${userid}</td>
				</tr>
				<tr>
					<td><b>Password</b></td>
					<td>${password}</td>
				</tr>
			</table>
		</div>
		
		<div> 
			<p>Kind regards</p>
			<p>Kevin</p>
		</div>
		
	</body>
</html>