<!doctype html>
<html lang="en">
	<head>
	    <meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	    <meta http-equiv="X-UA-Compatible" content="ie=edge">
	    <title>Arenella-ICT</title>
	</head>
	<body>
		<div style="margin-top: 10px">Dear ${firstname}</div>
		
		<p>
		I have set you up with a new Recruiter account. You currently have a 100% free Credit based subscription account. This allows you to:
			<ul>
				<li>Make ${cvDownloads} CV downloads each week</li>
				<li>Make ${jobBoardPosts} Posts on the job board each week</li>
				<li>Make ${marketPlacePosts} Posts on the marketplace each week</li>
			</ul>
		You will receive new credits each Monday
		</p>
		<p>
		You can upgrade to a paid subscription at any time. A paid subscription allows you to:
		<ul>
				<li>Make unlimeted CV downloads</li>
				<li>Make unlimited Posts on the job board each week</li>
				<li>Make unlimited Posts on the marketplace each week</li>
				<li>Gives you access to additional Candidates that are in the system but on a project</li>
				<li>Gives you access to candidates that require sponsorship</li>
			</ul>
		</p>
	
		<P>
			<a href="https://www.arenella-ict.com">https://www.arenella-ict.com</a>
		</P>
	
		<h3>Your login details are </h3>
	
		<div>
			<table>
				<tr>
					<td><b>Username</b></td>
					<td>${userid}</td>
				</tr>
				<tr>
					<td><b>Password</b></td>
					<td>${password}</td>
				</tr>
			</table>
		</div>
		
		<p>Feature available on the platform include:</p>
		
		<h3>Suggestions</h3>
		<p>This is an advanced search tool. It returns the best matches based upon the combination of filters selected by you</p>
		
		<h3>Job Board</h3>
		<p>You can add your open positions to the Job board. The advert's you place will be actively promoted within a network of 28000+ connections. </p>
		
		<h3>Marketplace</h3>
		<p>The marketplace allows collaboration between recruiters so that you can request candidates for positions you are trying to fill. </p>
		
		<div> 
			<p>Kind regards</p>
			<p>Kevin</p>
		</div>
		
	</body>
</html>