insert into curriculum.skills (skill) values ('logstash');
insert into curriculum.skills (skill) values ('cisco');
insert into curriculum.skills (skill) values ('switches');
insert into curriculum.skills (skill) values ('routers');
insert into curriculum.skills (skill) values ('liq');
insert into curriculum.skills (skill) values ('keras');
insert into curriculum.skills (skill) values ('morello');
insert into curriculum.skills (skill) values ('rest');
insert into curriculum.skills (skill) values ('microservices');
insert into curriculum.skills (skill) values ('budget');
insert into curriculum.skills (skill) values ('ssas');
insert into curriculum.skills (skill) values ('php');
insert into curriculum.skills (skill) values ('manual test');
insert into curriculum.skills (skill) values ('cloudtrail');
insert into curriculum.skills (skill) values ('software engineer in test');
insert into curriculum.skills (skill) values ('.net');
insert into curriculum.skills (skill) values ('oracle reports');
insert into curriculum.skills (skill) values ('psd');
insert into curriculum.skills (skill) values ('erlang');
insert into curriculum.skills (skill) values ('open radius');
insert into curriculum.skills (skill) values ('jdbc');
insert into curriculum.skills (skill) values ('d3.js');
insert into curriculum.skills (skill) values ('perl');
insert into curriculum.skills (skill) values ('openvpn');
insert into curriculum.skills (skill) values ('pegasystems');
insert into curriculum.skills (skill) values ('junit');
insert into curriculum.skills (skill) values ('guvnor');
insert into curriculum.skills (skill) values ('defects logging');
insert into curriculum.skills (skill) values ('assembler');
insert into curriculum.skills (skill) values ('datacenter');
insert into curriculum.skills (skill) values ('lightsail');
insert into curriculum.skills (skill) values ('windows');
insert into curriculum.skills (skill) values ('ospf');
insert into curriculum.skills (skill) values ('infrastructure');
insert into curriculum.skills (skill) values ('sprint planning');
insert into curriculum.skills (skill) values ('excahange server');
insert into curriculum.skills (skill) values ('finance');
insert into curriculum.skills (skill) values ('web services');
insert into curriculum.skills (skill) values ('gpdr');
insert into curriculum.skills (skill) values ('quality center');
insert into curriculum.skills (skill) values ('jasmine');
insert into curriculum.skills (skill) values ('redis');
insert into curriculum.skills (skill) values ('disaster recovery');
insert into curriculum.skills (skill) values ('spock');
insert into curriculum.skills (skill) values ('karate');
insert into curriculum.skills (skill) values ('optim studio');
insert into curriculum.skills (skill) values ('kanban');
insert into curriculum.skills (skill) values ('defect management');
insert into curriculum.skills (skill) values ('bi developer');
insert into curriculum.skills (skill) values ('hardware');
insert into curriculum.skills (skill) values ('rasberry pi');
insert into curriculum.skills (skill) values ('vsamlite');
insert into curriculum.skills (skill) values ('angular.js');
insert into curriculum.skills (skill) values ('angular8');
insert into curriculum.skills (skill) values ('centos');
insert into curriculum.skills (skill) values ('dojo');
insert into curriculum.skills (skill) values ('mvvm-c');
insert into curriculum.skills (skill) values ('artifactory');
insert into curriculum.skills (skill) values ('prpc');
insert into curriculum.skills (skill) values ('lead developer');
insert into curriculum.skills (skill) values ('falcon');
insert into curriculum.skills (skill) values ('linear regression');
insert into curriculum.skills (skill) values ('firewalls');
insert into curriculum.skills (skill) values ('bugzilla');
insert into curriculum.skills (skill) values ('random forest');
insert into curriculum.skills (skill) values ('visual studio code');
insert into curriculum.skills (skill) values ('tensorflow');
insert into curriculum.skills (skill) values ('arduino');
insert into curriculum.skills (skill) values ('telecoms');
insert into curriculum.skills (skill) values ('graphql');
insert into curriculum.skills (skill) values ('xgboost');
insert into curriculum.skills (skill) values ('vtam');
insert into curriculum.skills (skill) values ('vlan’s');
insert into curriculum.skills (skill) values ('chai');
insert into curriculum.skills (skill) values ('lucidchart');
insert into curriculum.skills (skill) values ('micro services');
insert into curriculum.skills (skill) values ('uat');
insert into curriculum.skills (skill) values ('plotly');
insert into curriculum.skills (skill) values ('jupyter notebook');
insert into curriculum.skills (skill) values ('reactjs');
insert into curriculum.skills (skill) values ('siebel');
insert into curriculum.skills (skill) values ('db2');
insert into curriculum.skills (skill) values ('webservice');
insert into curriculum.skills (skill) values ('iaas');
insert into curriculum.skills (skill) values ('sparql');
insert into curriculum.skills (skill) values ('citrix');
insert into curriculum.skills (skill) values ('swot');
insert into curriculum.skills (skill) values ('owl/rdf');
insert into curriculum.skills (skill) values ('naghos');
insert into curriculum.skills (skill) values ('cucumber');
insert into curriculum.skills (skill) values ('circleci');
insert into curriculum.skills (skill) values ('javamail');
insert into curriculum.skills (skill) values ('functional testing');
insert into curriculum.skills (skill) values ('unit testing');
insert into curriculum.skills (skill) values ('pl/sql');
insert into curriculum.skills (skill) values ('dot net');
insert into curriculum.skills (skill) values ('git and github');
insert into curriculum.skills (skill) values ('gatsby');
insert into curriculum.skills (skill) values ('ops');
insert into curriculum.skills (skill) values ('dba');
insert into curriculum.skills (skill) values ('http server');
insert into curriculum.skills (skill) values ('dbb');
insert into curriculum.skills (skill) values ('end to end');
insert into curriculum.skills (skill) values ('junos');
insert into curriculum.skills (skill) values ('eclipse');
insert into curriculum.skills (skill) values ('hl7');
insert into curriculum.skills (skill) values ('dbs');
insert into curriculum.skills (skill) values ('specflow');
insert into curriculum.skills (skill) values ('instructor');
insert into curriculum.skills (skill) values ('qlik sense');
insert into curriculum.skills (skill) values ('novell');
insert into curriculum.skills (skill) values ('testing methodologies');
insert into curriculum.skills (skill) values ('fibre');
insert into curriculum.skills (skill) values ('ssis');
insert into curriculum.skills (skill) values ('dhtml');
insert into curriculum.skills (skill) values ('soap');
insert into curriculum.skills (skill) values ('prtg');
insert into curriculum.skills (skill) values ('regresstion');
insert into curriculum.skills (skill) values ('logistics');
insert into curriculum.skills (skill) values ('mockito');
insert into curriculum.skills (skill) values ('netbackup');
insert into curriculum.skills (skill) values ('banking');
insert into curriculum.skills (skill) values ('mailcamp');
insert into curriculum.skills (skill) values ('smartstream');
insert into curriculum.skills (skill) values ('ued');
insert into curriculum.skills (skill) values ('group policy');
insert into curriculum.skills (skill) values ('audits');
insert into curriculum.skills (skill) values ('protcols');
insert into curriculum.skills (skill) values ('requirements');
insert into curriculum.skills (skill) values ('chrome dev tools');
insert into curriculum.skills (skill) values ('ddd');
insert into curriculum.skills (skill) values ('pytest');
insert into curriculum.skills (skill) values ('smoke testing');
insert into curriculum.skills (skill) values ('zoom');
insert into curriculum.skills (skill) values ('velocity');
insert into curriculum.skills (skill) values ('microsoft office 365');
insert into curriculum.skills (skill) values ('ddt');
insert into curriculum.skills (skill) values ('mobile testing');
insert into curriculum.skills (skill) values ('wireless');
insert into curriculum.skills (skill) values ('gouvernance');
insert into curriculum.skills (skill) values ('servlet');
insert into curriculum.skills (skill) values ('ms powerpoint');
insert into curriculum.skills (skill) values ('tenable');
insert into curriculum.skills (skill) values ('medm');
insert into curriculum.skills (skill) values ('asp.net mvc core');
insert into curriculum.skills (skill) values ('office365');
insert into curriculum.skills (skill) values ('white box');
insert into curriculum.skills (skill) values ('rally');
insert into curriculum.skills (skill) values ('google studio data');
insert into curriculum.skills (skill) values ('rest assured');
insert into curriculum.skills (skill) values ('ssms');
insert into curriculum.skills (skill) values ('ms sql');
insert into curriculum.skills (skill) values ('adobe indesign');
insert into curriculum.skills (skill) values ('agile');
insert into curriculum.skills (skill) values ('abap');
insert into curriculum.skills (skill) values ('netscape');
insert into curriculum.skills (skill) values ('prototyping');
insert into curriculum.skills (skill) values ('vtubes');
insert into curriculum.skills (skill) values ('redgate');
insert into curriculum.skills (skill) values ('test rail');
insert into curriculum.skills (skill) values ('webstorm');
insert into curriculum.skills (skill) values ('industrial cybersecurity');
insert into curriculum.skills (skill) values ('spark');
insert into curriculum.skills (skill) values ('assembly');
insert into curriculum.skills (skill) values ('embedded');
insert into curriculum.skills (skill) values ('qas');
insert into curriculum.skills (skill) values ('jax-ws');
insert into curriculum.skills (skill) values ('system. regression');
insert into curriculum.skills (skill) values ('winforms');
insert into curriculum.skills (skill) values ('ms azuer');
insert into curriculum.skills (skill) values ('algosec');
insert into curriculum.skills (skill) values ('private cloud');
insert into curriculum.skills (skill) values ('ui testing');
insert into curriculum.skills (skill) values ('latex');
insert into curriculum.skills (skill) values ('vb .net');
insert into curriculum.skills (skill) values ('ethereum');
insert into curriculum.skills (skill) values ('technical architecture');
insert into curriculum.skills (skill) values ('game dev');
insert into curriculum.skills (skill) values ('ssrs');
insert into curriculum.skills (skill) values ('azuer');
insert into curriculum.skills (skill) values ('access control');
insert into curriculum.skills (skill) values ('security audits');
insert into curriculum.skills (skill) values ('teamplayer');
insert into curriculum.skills (skill) values ('r studio');
insert into curriculum.skills (skill) values ('test');
insert into curriculum.skills (skill) values ('ms sql server');
insert into curriculum.skills (skill) values ('istqb certified tester');
insert into curriculum.skills (skill) values ('xcode');
insert into curriculum.skills (skill) values ('microservice architecture');
insert into curriculum.skills (skill) values ('miscrosoft');
insert into curriculum.skills (skill) values ('drupal');
insert into curriculum.skills (skill) values ('nunit');
insert into curriculum.skills (skill) values ('hsrp');
insert into curriculum.skills (skill) values ('sail point');
insert into curriculum.skills (skill) values ('tech support');
insert into curriculum.skills (skill) values ('ssl certificates');
insert into curriculum.skills (skill) values ('3d modelling');
insert into curriculum.skills (skill) values ('redshift');
insert into curriculum.skills (skill) values ('uml');
insert into curriculum.skills (skill) values ('service delivery');
insert into curriculum.skills (skill) values ('fortran');
insert into curriculum.skills (skill) values ('solr');
insert into curriculum.skills (skill) values ('visualizations');
insert into curriculum.skills (skill) values ('appium');
insert into curriculum.skills (skill) values ('regression');
insert into curriculum.skills (skill) values ('servlets');
insert into curriculum.skills (skill) values ('system admin');
insert into curriculum.skills (skill) values ('css 3');
insert into curriculum.skills (skill) values ('dreamweaver');
insert into curriculum.skills (skill) values ('defect tracking');
insert into curriculum.skills (skill) values ('html 5');
insert into curriculum.skills (skill) values ('certified scrum master');
insert into curriculum.skills (skill) values ('ms excel');
insert into curriculum.skills (skill) values ('uipath');
insert into curriculum.skills (skill) values ('python');
insert into curriculum.skills (skill) values ('lexmark');
insert into curriculum.skills (skill) values ('pythom');
insert into curriculum.skills (skill) values ('dns');
insert into curriculum.skills (skill) values ('soap ui');
insert into curriculum.skills (skill) values ('fitnesse');
insert into curriculum.skills (skill) values ('dynamo');
insert into curriculum.skills (skill) values ('classification');
insert into curriculum.skills (skill) values ('servicenow');
insert into curriculum.skills (skill) values ('upm');
insert into curriculum.skills (skill) values ('prince2');
insert into curriculum.skills (skill) values ('vs code');
insert into curriculum.skills (skill) values ('mi testing');
insert into curriculum.skills (skill) values ('trading');
insert into curriculum.skills (skill) values ('lsmw');
insert into curriculum.skills (skill) values ('vue.js');
insert into curriculum.skills (skill) values ('mac');
insert into curriculum.skills (skill) values ('apache tomcat');
insert into curriculum.skills (skill) values ('zephyr');
insert into curriculum.skills (skill) values ('is-is');
insert into curriculum.skills (skill) values ('orcad');
insert into curriculum.skills (skill) values ('government');
insert into curriculum.skills (skill) values ('data visualtization');
insert into curriculum.skills (skill) values ('citrix gateway');
insert into curriculum.skills (skill) values ('qualitycenter');
insert into curriculum.skills (skill) values ('sixsigma');
insert into curriculum.skills (skill) values ('pandas');
insert into curriculum.skills (skill) values ('testflight');
insert into curriculum.skills (skill) values ('urs');
insert into curriculum.skills (skill) values ('google analytics');
insert into curriculum.skills (skill) values ('winform application');
insert into curriculum.skills (skill) values ('tso/e');
insert into curriculum.skills (skill) values ('soap api testing');
insert into curriculum.skills (skill) values ('networking');
insert into curriculum.skills (skill) values ('vb.net');
insert into curriculum.skills (skill) values ('service transition');
insert into curriculum.skills (skill) values ('microservice testing');
insert into curriculum.skills (skill) values ('java script');
insert into curriculum.skills (skill) values ('catos');
insert into curriculum.skills (skill) values ('shell scripting');
insert into curriculum.skills (skill) values ('mcp');
insert into curriculum.skills (skill) values ('web testing');
insert into curriculum.skills (skill) values ('hyper v');
insert into curriculum.skills (skill) values ('mobile design');
insert into curriculum.skills (skill) values ('infactructure');
insert into curriculum.skills (skill) values ('ideal');
insert into curriculum.skills (skill) values ('nginx');
insert into curriculum.skills (skill) values ('vbscript');
insert into curriculum.skills (skill) values ('ca-rpf');
insert into curriculum.skills (skill) values ('telon');
insert into curriculum.skills (skill) values ('joomla');
insert into curriculum.skills (skill) values ('competence center');
insert into curriculum.skills (skill) values ('helpdesk');
insert into curriculum.skills (skill) values ('director of it');
insert into curriculum.skills (skill) values ('via solutions provider');
insert into curriculum.skills (skill) values ('cloud infrastructure (iaas');
insert into curriculum.skills (skill) values ('spanning tree');
insert into curriculum.skills (skill) values ('data governance');
insert into curriculum.skills (skill) values ('google drive & dropbox');
insert into curriculum.skills (skill) values ('dsl');
insert into curriculum.skills (skill) values ('stakeholder managemet');
insert into curriculum.skills (skill) values ('nexus');
insert into curriculum.skills (skill) values ('owasp');
insert into curriculum.skills (skill) values ('mongoose');
insert into curriculum.skills (skill) values ('postgresql');
insert into curriculum.skills (skill) values ('willing to relocate');
insert into curriculum.skills (skill) values ('quality studio');
insert into curriculum.skills (skill) values ('leadership');
insert into curriculum.skills (skill) values ('gamemechanics');
insert into curriculum.skills (skill) values ('pythin');
insert into curriculum.skills (skill) values ('ccna2');
insert into curriculum.skills (skill) values ('flaui');
insert into curriculum.skills (skill) values ('big data analytics');
insert into curriculum.skills (skill) values ('splunk enterprise');
insert into curriculum.skills (skill) values ('windows servers');
insert into curriculum.skills (skill) values ('kotlin');
insert into curriculum.skills (skill) values ('solar winds');
insert into curriculum.skills (skill) values ('mfa');
insert into curriculum.skills (skill) values ('test autormation framework');
insert into curriculum.skills (skill) values ('ruby');
insert into curriculum.skills (skill) values ('requirements analysis');
insert into curriculum.skills (skill) values ('illistrator');
insert into curriculum.skills (skill) values ('ocgt');
insert into curriculum.skills (skill) values ('network monitoring');
insert into curriculum.skills (skill) values ('clustering');
insert into curriculum.skills (skill) values ('stakeholder meetings');
insert into curriculum.skills (skill) values ('curl');
insert into curriculum.skills (skill) values ('hp-uft');
insert into curriculum.skills (skill) values ('page object model');
insert into curriculum.skills (skill) values ('mangodb');
insert into curriculum.skills (skill) values ('uwp');
insert into curriculum.skills (skill) values ('broadband');
insert into curriculum.skills (skill) values ('mvvm');
insert into curriculum.skills (skill) values ('devops');
insert into curriculum.skills (skill) values ('mvs/sp');
insert into curriculum.skills (skill) values ('java-script');
insert into curriculum.skills (skill) values ('service now');
insert into curriculum.skills (skill) values ('nmap');
insert into curriculum.skills (skill) values ('system design');
insert into curriculum.skills (skill) values ('bluecat');
insert into curriculum.skills (skill) values ('dwh');
insert into curriculum.skills (skill) values ('cassandra');
insert into curriculum.skills (skill) values ('restassured');
insert into curriculum.skills (skill) values ('maternalize');
insert into curriculum.skills (skill) values ('smeserver');
insert into curriculum.skills (skill) values ('jasperreport');
insert into curriculum.skills (skill) values ('apache sqoop');
insert into curriculum.skills (skill) values ('websphere');
insert into curriculum.skills (skill) values ('switching');
insert into curriculum.skills (skill) values ('functional');
insert into curriculum.skills (skill) values ('six sigma');
insert into curriculum.skills (skill) values ('cmdb');
insert into curriculum.skills (skill) values ('manual testing');
insert into curriculum.skills (skill) values ('voiceover');
insert into curriculum.skills (skill) values ('test case creation');
insert into curriculum.skills (skill) values ('numpy');
insert into curriculum.skills (skill) values ('jmeter');
insert into curriculum.skills (skill) values ('backend testing');
insert into curriculum.skills (skill) values ('jupyter');
insert into curriculum.skills (skill) values ('iam');
insert into curriculum.skills (skill) values ('spring mvc');
insert into curriculum.skills (skill) values ('schetsen');
insert into curriculum.skills (skill) values ('angular 4');
insert into curriculum.skills (skill) values ('tcs smarttest');
insert into curriculum.skills (skill) values ('people');
insert into curriculum.skills (skill) values ('microtek');
insert into curriculum.skills (skill) values ('html 32 hours per week');
insert into curriculum.skills (skill) values ('ibm');
insert into curriculum.skills (skill) values ('umbraco');
insert into curriculum.skills (skill) values ('babel');
insert into curriculum.skills (skill) values ('enterprise architect');
insert into curriculum.skills (skill) values ('asus');
insert into curriculum.skills (skill) values ('procurve');
insert into curriculum.skills (skill) values ('typescript en visual studio');
insert into curriculum.skills (skill) values ('wordpress');
insert into curriculum.skills (skill) values ('cordava');
insert into curriculum.skills (skill) values ('automation anywhere');
insert into curriculum.skills (skill) values ('oauth2');
insert into curriculum.skills (skill) values ('web design');
insert into curriculum.skills (skill) values ('sccm');
insert into curriculum.skills (skill) values ('prometheous.io');
insert into curriculum.skills (skill) values ('open api');
insert into curriculum.skills (skill) values ('mysql');
insert into curriculum.skills (skill) values ('workspaces');
insert into curriculum.skills (skill) values ('no banking roles');
insert into curriculum.skills (skill) values ('spylog');
insert into curriculum.skills (skill) values ('qtp');
insert into curriculum.skills (skill) values ('customer relations');
insert into curriculum.skills (skill) values ('mongo');
insert into curriculum.skills (skill) values ('user stories');
insert into curriculum.skills (skill) values ('integration testing');
insert into curriculum.skills (skill) values ('juniper network');
insert into curriculum.skills (skill) values ('autocad');
insert into curriculum.skills (skill) values ('cadis');
insert into curriculum.skills (skill) values ('deep learning');
insert into curriculum.skills (skill) values ('linux');
insert into curriculum.skills (skill) values ('debian');
insert into curriculum.skills (skill) values ('twig');
insert into curriculum.skills (skill) values ('ionic');
insert into curriculum.skills (skill) values ('clarity ppm');
insert into curriculum.skills (skill) values ('middleware');
insert into curriculum.skills (skill) values ('azure data lake');
insert into curriculum.skills (skill) values ('free-to-playdesign');
insert into curriculum.skills (skill) values ('beats');
insert into curriculum.skills (skill) values ('network administration');
insert into curriculum.skills (skill) values ('games tester');
insert into curriculum.skills (skill) values ('event sourcing');
insert into curriculum.skills (skill) values ('responsive design');
insert into curriculum.skills (skill) values ('stakeholder engagement');
insert into curriculum.skills (skill) values ('olap');
insert into curriculum.skills (skill) values ('bash');
insert into curriculum.skills (skill) values ('stibo');
insert into curriculum.skills (skill) values ('cqrs');
insert into curriculum.skills (skill) values ('jax-rs');
insert into curriculum.skills (skill) values ('isdn');
insert into curriculum.skills (skill) values ('coffee script');
insert into curriculum.skills (skill) values ('it operations');
insert into curriculum.skills (skill) values ('draytek');
insert into curriculum.skills (skill) values ('ui design');
insert into curriculum.skills (skill) values ('bigquery');
insert into curriculum.skills (skill) values ('logistic regression');
insert into curriculum.skills (skill) values ('eggplant');
insert into curriculum.skills (skill) values ('azure');
insert into curriculum.skills (skill) values ('data analytics');
insert into curriculum.skills (skill) values ('font awesome');
insert into curriculum.skills (skill) values ('impala');
insert into curriculum.skills (skill) values ('thinapp');
insert into curriculum.skills (skill) values ('kohana');
insert into curriculum.skills (skill) values ('vba');
insert into curriculum.skills (skill) values ('azure datafactory');
insert into curriculum.skills (skill) values ('struts');
insert into curriculum.skills (skill) values ('lenovo');
insert into curriculum.skills (skill) values ('microsoft office excel');
insert into curriculum.skills (skill) values ('socket.io');
insert into curriculum.skills (skill) values ('nagios');
insert into curriculum.skills (skill) values ('pascal');
insert into curriculum.skills (skill) values ('architect');
insert into curriculum.skills (skill) values ('eae');
insert into curriculum.skills (skill) values ('bootstrap');
insert into curriculum.skills (skill) values ('it service');
insert into curriculum.skills (skill) values ('itilv3');
insert into curriculum.skills (skill) values ('eai');
insert into curriculum.skills (skill) values ('fireworks');
insert into curriculum.skills (skill) values ('objective c');
insert into curriculum.skills (skill) values ('iis');
insert into curriculum.skills (skill) values ('ec3');
insert into curriculum.skills (skill) values ('ec2');
insert into curriculum.skills (skill) values ('installation');
insert into curriculum.skills (skill) values ('pl-sql');
insert into curriculum.skills (skill) values ('microsoft project');
insert into curriculum.skills (skill) values ('vcp');
insert into curriculum.skills (skill) values ('entity framework');
insert into curriculum.skills (skill) values ('data modelling');
insert into curriculum.skills (skill) values ('via broker – objective c');
insert into curriculum.skills (skill) values ('webdriverio');
insert into curriculum.skills (skill) values ('excel');
insert into curriculum.skills (skill) values ('quasar');
insert into curriculum.skills (skill) values ('iseb');
insert into curriculum.skills (skill) values ('ebs');
insert into curriculum.skills (skill) values ('bokeh');
insert into curriculum.skills (skill) values ('vdi');
insert into curriculum.skills (skill) values ('bootstra[');
insert into curriculum.skills (skill) values ('java enterprise architecture');
insert into curriculum.skills (skill) values ('micosercices');
insert into curriculum.skills (skill) values ('checkpoint');
insert into curriculum.skills (skill) values ('systemdesign');
insert into curriculum.skills (skill) values ('trello');
insert into curriculum.skills (skill) values ('load runner');
insert into curriculum.skills (skill) values ('work permit for netherlands');
insert into curriculum.skills (skill) values ('symfony');
insert into curriculum.skills (skill) values ('axis');
insert into curriculum.skills (skill) values ('interim management');
insert into curriculum.skills (skill) values ('database design');
insert into curriculum.skills (skill) values ('j2ee');
insert into curriculum.skills (skill) values ('html');
insert into curriculum.skills (skill) values ('mvs/xa');
insert into curriculum.skills (skill) values ('open to free internship');
insert into curriculum.skills (skill) values ('jaav');
insert into curriculum.skills (skill) values ('jira');
insert into curriculum.skills (skill) values ('laravel');
insert into curriculum.skills (skill) values ('network security');
insert into curriculum.skills (skill) values ('ubuntu');
insert into curriculum.skills (skill) values ('maven');
insert into curriculum.skills (skill) values ('coolgen');
insert into curriculum.skills (skill) values ('asp .net');
insert into curriculum.skills (skill) values ('edi');
insert into curriculum.skills (skill) values ('saas)');
insert into curriculum.skills (skill) values ('stlc');
insert into curriculum.skills (skill) values ('maya');
insert into curriculum.skills (skill) values ('dfdss');
insert into curriculum.skills (skill) values ('adobe photoshop');
insert into curriculum.skills (skill) values ('network congiguration');
insert into curriculum.skills (skill) values ('htlm');
insert into curriculum.skills (skill) values ('graphsql');
insert into curriculum.skills (skill) values ('routing and switching');
insert into curriculum.skills (skill) values ('ogone');
insert into curriculum.skills (skill) values ('configuration');
insert into curriculum.skills (skill) values ('pen testing');
insert into curriculum.skills (skill) values ('wcf service');
insert into curriculum.skills (skill) values ('windows 10');
insert into curriculum.skills (skill) values ('rust');
insert into curriculum.skills (skill) values ('operations');
insert into curriculum.skills (skill) values ('solid works');
insert into curriculum.skills (skill) values ('java 8');
insert into curriculum.skills (skill) values ('data visualization');
insert into curriculum.skills (skill) values ('mvc');
insert into curriculum.skills (skill) values ('dhcp');
insert into curriculum.skills (skill) values ('clearos');
insert into curriculum.skills (skill) values ('kuka robot');
insert into curriculum.skills (skill) values ('automation dashboards');
insert into curriculum.skills (skill) values ('non-functional');
insert into curriculum.skills (skill) values ('toad');
insert into curriculum.skills (skill) values ('mvs');
insert into curriculum.skills (skill) values ('nmon');
insert into curriculum.skills (skill) values ('performance');
insert into curriculum.skills (skill) values ('mavem portlets');
insert into curriculum.skills (skill) values ('infasctructure');
insert into curriculum.skills (skill) values ('respowerfuse');
insert into curriculum.skills (skill) values ('pthreads');
insert into curriculum.skills (skill) values ('egb');
insert into curriculum.skills (skill) values ('vega-lite');
insert into curriculum.skills (skill) values ('html5');
insert into curriculum.skills (skill) values ('html4');
insert into curriculum.skills (skill) values ('perfmon');
insert into curriculum.skills (skill) values ('ios');
insert into curriculum.skills (skill) values ('iot');
insert into curriculum.skills (skill) values ('0365');
insert into curriculum.skills (skill) values ('rad');
insert into curriculum.skills (skill) values ('graduate');
insert into curriculum.skills (skill) values ('hp quicktest');
insert into curriculum.skills (skill) values ('subnets');
insert into curriculum.skills (skill) values ('scom');
insert into curriculum.skills (skill) values ('vim');
insert into curriculum.skills (skill) values ('vip');
insert into curriculum.skills (skill) values ('kibana');
insert into curriculum.skills (skill) values ('jive');
insert into curriculum.skills (skill) values ('chassis cluster');
insert into curriculum.skills (skill) values ('sails');
insert into curriculum.skills (skill) values ('shell programing');
insert into curriculum.skills (skill) values ('ips');
insert into curriculum.skills (skill) values ('cocoa');
insert into curriculum.skills (skill) values ('ifrs');
insert into curriculum.skills (skill) values ('aruba');
insert into curriculum.skills (skill) values ('esxi');
insert into curriculum.skills (skill) values ('planning');
insert into curriculum.skills (skill) values ('next.js');
insert into curriculum.skills (skill) values ('zeplin');
insert into curriculum.skills (skill) values ('epress');
insert into curriculum.skills (skill) values ('wireframing');
insert into curriculum.skills (skill) values ('manual');
insert into curriculum.skills (skill) values ('prestashop');
insert into curriculum.skills (skill) values ('web forms');
insert into curriculum.skills (skill) values ('dev-extreme');
insert into curriculum.skills (skill) values ('cisci');
insert into curriculum.skills (skill) values ('certified');
insert into curriculum.skills (skill) values ('ejb');
insert into curriculum.skills (skill) values ('boost c++');
insert into curriculum.skills (skill) values ('msbi');
insert into curriculum.skills (skill) values ('haskell');
insert into curriculum.skills (skill) values ('azure databricks');
insert into curriculum.skills (skill) values ('operations mangement');
insert into curriculum.skills (skill) values ('strm');
insert into curriculum.skills (skill) values ('knockoutjs');
insert into curriculum.skills (skill) values ('spring boot');
insert into curriculum.skills (skill) values ('swing');
insert into curriculum.skills (skill) values ('nvda');
insert into curriculum.skills (skill) values ('full stack');
insert into curriculum.skills (skill) values ('senior unix administrator');
insert into curriculum.skills (skill) values ('hiportfolio');
insert into curriculum.skills (skill) values ('iso');
insert into curriculum.skills (skill) values ('scss');
insert into curriculum.skills (skill) values ('spring');
insert into curriculum.skills (skill) values ('j2me');
insert into curriculum.skills (skill) values ('ispf');
insert into curriculum.skills (skill) values ('google cloud');
insert into curriculum.skills (skill) values ('multithreading');
insert into curriculum.skills (skill) values ('elb');
insert into curriculum.skills (skill) values ('vms');
insert into curriculum.skills (skill) values ('swift');
insert into curriculum.skills (skill) values ('it gouverncance');
insert into curriculum.skills (skill) values ('res');
insert into curriculum.skills (skill) values ('javascript and css');
insert into curriculum.skills (skill) values ('zabbix');
insert into curriculum.skills (skill) values ('elk');
insert into curriculum.skills (skill) values ('scons');
insert into curriculum.skills (skill) values ('android studio');
insert into curriculum.skills (skill) values ('elt');
insert into curriculum.skills (skill) values ('ado');
insert into curriculum.skills (skill) values ('(from june) js');
insert into curriculum.skills (skill) values ('shell');
insert into curriculum.skills (skill) values ('incident mangagment');
insert into curriculum.skills (skill) values ('mdx scripts');
insert into curriculum.skills (skill) values ('emc');
insert into curriculum.skills (skill) values ('exchange');
insert into curriculum.skills (skill) values ('android sdk');
insert into curriculum.skills (skill) values ('vnx');
insert into curriculum.skills (skill) values ('dynamic web pages');
insert into curriculum.skills (skill) values ('svelte');
insert into curriculum.skills (skill) values ('codeigniter');
insert into curriculum.skills (skill) values ('visual basic');
insert into curriculum.skills (skill) values ('oauth');
insert into curriculum.skills (skill) values ('c/c++');
insert into curriculum.skills (skill) values ('phonenumberkit');
insert into curriculum.skills (skill) values ('ivr');
insert into curriculum.skills (skill) values ('k8s');
insert into curriculum.skills (skill) values ('vpc');
insert into curriculum.skills (skill) values ('experince as intern');
insert into curriculum.skills (skill) values ('rtc/ucd');
insert into curriculum.skills (skill) values ('jest');
insert into curriculum.skills (skill) values ('ux research');
insert into curriculum.skills (skill) values ('octopus deploy');
insert into curriculum.skills (skill) values ('vpn');
insert into curriculum.skills (skill) values ('jndi');
insert into curriculum.skills (skill) values ('c++');
insert into curriculum.skills (skill) values ('webdevelopment');
insert into curriculum.skills (skill) values ('tomcat');
insert into curriculum.skills (skill) values ('neural networks');
insert into curriculum.skills (skill) values ('sanity');
insert into curriculum.skills (skill) values ('martis');
insert into curriculum.skills (skill) values ('oracle 10g');
insert into curriculum.skills (skill) values ('slack');
insert into curriculum.skills (skill) values ('rip');
insert into curriculum.skills (skill) values ('ris');
insert into curriculum.skills (skill) values ('nat');
insert into curriculum.skills (skill) values ('sybase');
insert into curriculum.skills (skill) values ('testing');
insert into curriculum.skills (skill) values ('vrf');
insert into curriculum.skills (skill) values ('hudson');
insert into curriculum.skills (skill) values ('oltp');
insert into curriculum.skills (skill) values ('query optimization');
insert into curriculum.skills (skill) values ('system');
insert into curriculum.skills (skill) values ('larvel');
insert into curriculum.skills (skill) values ('hp alm');
insert into curriculum.skills (skill) values ('jupyter notebooks');
insert into curriculum.skills (skill) values ('microsoft office visio');
insert into curriculum.skills (skill) values ('jama');
insert into curriculum.skills (skill) values ('ms office');
insert into curriculum.skills (skill) values ('exact globe 2003');
insert into curriculum.skills (skill) values ('24 hours p/w');
insert into curriculum.skills (skill) values ('software design');
insert into curriculum.skills (skill) values ('ado.net');
insert into curriculum.skills (skill) values ('vse');
insert into curriculum.skills (skill) values ('azure devops');
insert into curriculum.skills (skill) values ('paloalto');
insert into curriculum.skills (skill) values ('aix');
insert into curriculum.skills (skill) values ('aws server');
insert into curriculum.skills (skill) values ('e-learning');
insert into curriculum.skills (skill) values ('erp');
insert into curriculum.skills (skill) values ('ingenico');
insert into curriculum.skills (skill) values ('sonarqube');
insert into curriculum.skills (skill) values ('system testing');
insert into curriculum.skills (skill) values ('j2se');
insert into curriculum.skills (skill) values ('nacl');
insert into curriculum.skills (skill) values ('nuxt.js');
insert into curriculum.skills (skill) values ('vtp');
insert into curriculum.skills (skill) values ('business process');
insert into curriculum.skills (skill) values ('esb');
insert into curriculum.skills (skill) values ('governance');
insert into curriculum.skills (skill) values ('google  analytics');
insert into curriculum.skills (skill) values ('vue');
insert into curriculum.skills (skill) values ('indesign');
insert into curriculum.skills (skill) values ('p&l management');
insert into curriculum.skills (skill) values ('c4.5');
insert into curriculum.skills (skill) values ('windows server');
insert into curriculum.skills (skill) values ('etl');
insert into curriculum.skills (skill) values ('alm');
insert into curriculum.skills (skill) values ('game theory');
insert into curriculum.skills (skill) values ('network admin');
insert into curriculum.skills (skill) values ('bods');
insert into curriculum.skills (skill) values ('capistrano');
insert into curriculum.skills (skill) values ('apis');
insert into curriculum.skills (skill) values ('basecamp');
insert into curriculum.skills (skill) values ('smarty');
insert into curriculum.skills (skill) values ('oracle sql');
insert into curriculum.skills (skill) values ('mcafee');
insert into curriculum.skills (skill) values ('unix');
insert into curriculum.skills (skill) values ('elixir');
insert into curriculum.skills (skill) values ('teraform');
insert into curriculum.skills (skill) values ('dplyr');
insert into curriculum.skills (skill) values ('grunt');
insert into curriculum.skills (skill) values ('evc');
insert into curriculum.skills (skill) values ('mongodb');
insert into curriculum.skills (skill) values ('gulpjs');
insert into curriculum.skills (skill) values ('frontify');
insert into curriculum.skills (skill) values ('magento');
insert into curriculum.skills (skill) values ('link api testing');
insert into curriculum.skills (skill) values ('google colab');
insert into curriculum.skills (skill) values ('cyber security');
insert into curriculum.skills (skill) values ('rpc');
insert into curriculum.skills (skill) values ('istqb');
insert into curriculum.skills (skill) values ('ant');
insert into curriculum.skills (skill) values ('rpg');
insert into curriculum.skills (skill) values ('xenapp');
insert into curriculum.skills (skill) values ('quartz');
insert into curriculum.skills (skill) values ('apache benchmark');
insert into curriculum.skills (skill) values ('naïve bayes');
insert into curriculum.skills (skill) values ('xslt');
insert into curriculum.skills (skill) values ('ethical hacking');
insert into curriculum.skills (skill) values ('scikit');
insert into curriculum.skills (skill) values ('strategy');
insert into curriculum.skills (skill) values ('axiom');
insert into curriculum.skills (skill) values ('data pipelines');
insert into curriculum.skills (skill) values ('test management');
insert into curriculum.skills (skill) values ('v-model');
insert into curriculum.skills (skill) values ('java');
insert into curriculum.skills (skill) values ('onenote');
insert into curriculum.skills (skill) values ('pivot');
insert into curriculum.skills (skill) values ('api');
insert into curriculum.skills (skill) values ('xamarin');
insert into curriculum.skills (skill) values ('juniper');
insert into curriculum.skills (skill) values ('nosql');
insert into curriculum.skills (skill) values ('supply chain management');
insert into curriculum.skills (skill) values ('quality assurance');
insert into curriculum.skills (skill) values ('matplotlib');
insert into curriculum.skills (skill) values ('flask');
insert into curriculum.skills (skill) values ('anlaysis');
insert into curriculum.skills (skill) values ('postmann api');
insert into curriculum.skills (skill) values ('flash');
insert into curriculum.skills (skill) values ('rsa');
insert into curriculum.skills (skill) values ('implemetation');
insert into curriculum.skills (skill) values ('mobility');
insert into curriculum.skills (skill) values ('business analyst');
insert into curriculum.skills (skill) values ('ms outlook');
insert into curriculum.skills (skill) values ('cissp');
insert into curriculum.skills (skill) values ('jaxb');
insert into curriculum.skills (skill) values ('db testing');
insert into curriculum.skills (skill) values ('jcl');
insert into curriculum.skills (skill) values ('rst');
insert into curriculum.skills (skill) values ('c4c');
insert into curriculum.skills (skill) values ('k-nn');
insert into curriculum.skills (skill) values ('encryption');
insert into curriculum.skills (skill) values ('rxswift');
insert into curriculum.skills (skill) values ('c++ .net');
insert into curriculum.skills (skill) values ('waterfall');
insert into curriculum.skills (skill) values ('pytorch');
insert into curriculum.skills (skill) values ('backbone');
insert into curriculum.skills (skill) values ('arm');
insert into curriculum.skills (skill) values ('websockets');
insert into curriculum.skills (skill) values ('rtc');
insert into curriculum.skills (skill) values ('gitflow');
insert into curriculum.skills (skill) values ('jaws');
insert into curriculum.skills (skill) values ('team management');
insert into curriculum.skills (skill) values ('appcenter');
insert into curriculum.skills (skill) values ('rtm');
insert into curriculum.skills (skill) values ('bower');
insert into curriculum.skills (skill) values ('rtp');
insert into curriculum.skills (skill) values ('gradle');
insert into curriculum.skills (skill) values ('rts');
insert into curriculum.skills (skill) values ('web analytics');
insert into curriculum.skills (skill) values ('asl');
insert into curriculum.skills (skill) values ('asp');
insert into curriculum.skills (skill) values ('administration');
insert into curriculum.skills (skill) values ('itbm');
insert into curriculum.skills (skill) values ('jee');
insert into curriculum.skills (skill) values ('rup');
insert into curriculum.skills (skill) values ('bitbucket');
insert into curriculum.skills (skill) values ('mantis');
insert into curriculum.skills (skill) values ('fritzbox');
insert into curriculum.skills (skill) values ('ecmascript');
insert into curriculum.skills (skill) values ('java 8 certified');
insert into curriculum.skills (skill) values ('software architecture');
insert into curriculum.skills (skill) values ('pipelines');
insert into curriculum.skills (skill) values ('atg');
insert into curriculum.skills (skill) values ('stripe');
insert into curriculum.skills (skill) values ('portfolio management');
insert into curriculum.skills (skill) values ('big data');
insert into curriculum.skills (skill) values ('ecma');
insert into curriculum.skills (skill) values ('yaml');
insert into curriculum.skills (skill) values ('sqlite');
insert into curriculum.skills (skill) values ('process improvement');
insert into curriculum.skills (skill) values ('thymeleaf');
insert into curriculum.skills (skill) values ('openmp');
insert into curriculum.skills (skill) values ('bootstrap json');
insert into curriculum.skills (skill) values ('flutter');
insert into curriculum.skills (skill) values ('node.js');
insert into curriculum.skills (skill) values ('computer forensics');
insert into curriculum.skills (skill) values ('tailwind');
insert into curriculum.skills (skill) values ('noc');
insert into curriculum.skills (skill) values ('android');
insert into curriculum.skills (skill) values ('raspberry pi');
insert into curriculum.skills (skill) values ('avg');
insert into curriculum.skills (skill) values ('sqlserver');
insert into curriculum.skills (skill) values ('ms exchange');
insert into curriculum.skills (skill) values ('file server');
insert into curriculum.skills (skill) values ('hadoop');
insert into curriculum.skills (skill) values ('samba');
insert into curriculum.skills (skill) values ('data analysis');
insert into curriculum.skills (skill) values ('information management');
insert into curriculum.skills (skill) values ('wan');
insert into curriculum.skills (skill) values ('npm');
insert into curriculum.skills (skill) values ('xhtml');
insert into curriculum.skills (skill) values ('awd');
insert into curriculum.skills (skill) values ('awk');
insert into curriculum.skills (skill) values ('sdet');
insert into curriculum.skills (skill) values ('acceptance testing');
insert into curriculum.skills (skill) values ('risk');
insert into curriculum.skills (skill) values ('aws');
insert into curriculum.skills (skill) values ('vm ware esx');
insert into curriculum.skills (skill) values ('web os');
insert into curriculum.skills (skill) values ('r programming');
insert into curriculum.skills (skill) values ('hyper-v');
insert into curriculum.skills (skill) values ('ci/cd');
insert into curriculum.skills (skill) values ('cart');
insert into curriculum.skills (skill) values ('change control');
insert into curriculum.skills (skill) values ('analysis and design');
insert into curriculum.skills (skill) values ('powershell');
insert into curriculum.skills (skill) values ('electron');
insert into curriculum.skills (skill) values ('wcd');
insert into curriculum.skills (skill) values ('wcf');
insert into curriculum.skills (skill) values ('charles proxy');
insert into curriculum.skills (skill) values ('ibm qradar');
insert into curriculum.skills (skill) values ('automation testing');
insert into curriculum.skills (skill) values ('auto-scaling');
insert into curriculum.skills (skill) values ('tibco');
insert into curriculum.skills (skill) values ('directory service');
insert into curriculum.skills (skill) values ('test ng');
insert into curriculum.skills (skill) values ('mediasurface');
insert into curriculum.skills (skill) values ('mainframe testing');
insert into curriculum.skills (skill) values ('ccna security');
insert into curriculum.skills (skill) values ('testing types');
insert into curriculum.skills (skill) values ('mantis automated testing');
insert into curriculum.skills (skill) values ('o365');
insert into curriculum.skills (skill) values ('skybox');
insert into curriculum.skills (skill) values ('web');
insert into curriculum.skills (skill) values ('spring rest');
insert into curriculum.skills (skill) values ('stress');
insert into curriculum.skills (skill) values ('material ui');
insert into curriculum.skills (skill) values ('(adn)');
insert into curriculum.skills (skill) values ('crossfilter.js');
insert into curriculum.skills (skill) values ('palo alto networks');
insert into curriculum.skills (skill) values ('gatsbyjs');
insert into curriculum.skills (skill) values ('shopify');
insert into curriculum.skills (skill) values ('vsphere');
insert into curriculum.skills (skill) values ('protractor');
insert into curriculum.skills (skill) values ('hypervisors');
insert into curriculum.skills (skill) values ('wfl');
insert into curriculum.skills (skill) values ('adobe xd');
insert into curriculum.skills (skill) values ('competitive intelligence');
insert into curriculum.skills (skill) values ('cloud');
insert into curriculum.skills (skill) values ('sauce labs');
insert into curriculum.skills (skill) values ('jms');
insert into curriculum.skills (skill) values ('cisco asa');
insert into curriculum.skills (skill) values ('ldap');
insert into curriculum.skills (skill) values ('webpack');
insert into curriculum.skills (skill) values ('asp.net');
insert into curriculum.skills (skill) values ('network design');
insert into curriculum.skills (skill) values ('open cart');
insert into curriculum.skills (skill) values ('trend analysis');
insert into curriculum.skills (skill) values ('springmvc');
insert into curriculum.skills (skill) values ('postgis');
insert into curriculum.skills (skill) values ('event planning');
insert into curriculum.skills (skill) values ('ipam');
insert into curriculum.skills (skill) values ('ms cluster');
insert into curriculum.skills (skill) values ('robot framework');
insert into curriculum.skills (skill) values ('astah');
insert into curriculum.skills (skill) values ('rail');
insert into curriculum.skills (skill) values ('talend');
insert into curriculum.skills (skill) values ('game design');
insert into curriculum.skills (skill) values ('visual studio');
insert into curriculum.skills (skill) values ('material-ui');
insert into curriculum.skills (skill) values ('backlog');
insert into curriculum.skills (skill) values ('sdlc');
insert into curriculum.skills (skill) values ('itil');
insert into curriculum.skills (skill) values ('react js');
insert into curriculum.skills (skill) values ('sonar');
insert into curriculum.skills (skill) values ('html & css');
insert into curriculum.skills (skill) values ('rsqlite');
insert into curriculum.skills (skill) values ('it management');
insert into curriculum.skills (skill) values ('ivanti');
insert into curriculum.skills (skill) values ('jpa');
insert into curriculum.skills (skill) values ('authentication');
insert into curriculum.skills (skill) values ('san');
insert into curriculum.skills (skill) values ('sap');
insert into curriculum.skills (skill) values ('sas');
insert into curriculum.skills (skill) values ('core java');
insert into curriculum.skills (skill) values ('jasper');
insert into curriculum.skills (skill) values ('puppet');
insert into curriculum.skills (skill) values ('django');
insert into curriculum.skills (skill) values ('sourcetree');
insert into curriculum.skills (skill) values ('shiny');
insert into curriculum.skills (skill) values ('frontend');
insert into curriculum.skills (skill) values ('opencv');
insert into curriculum.skills (skill) values ('digital marketing');
insert into curriculum.skills (skill) values ('mvs/esa');
insert into curriculum.skills (skill) values ('webservices');
insert into curriculum.skills (skill) values ('rest api');
insert into curriculum.skills (skill) values ('os/390');
insert into curriculum.skills (skill) values ('canon');
insert into curriculum.skills (skill) values ('sca');
insert into curriculum.skills (skill) values ('mssql server 2016');
insert into curriculum.skills (skill) values ('bau');
insert into curriculum.skills (skill) values ('javafx');
insert into curriculum.skills (skill) values ('c#');
insert into curriculum.skills (skill) values ('ad');
insert into curriculum.skills (skill) values ('leveldesign');
insert into curriculum.skills (skill) values ('documentation');
insert into curriculum.skills (skill) values ('hp qtp');
insert into curriculum.skills (skill) values ('ai');
insert into curriculum.skills (skill) values ('redhat');
insert into curriculum.skills (skill) values ('light gbm');
insert into curriculum.skills (skill) values ('veritas');
insert into curriculum.skills (skill) values ('incident management');
insert into curriculum.skills (skill) values ('ipsec');
insert into curriculum.skills (skill) values ('cocoa touch');
insert into curriculum.skills (skill) values ('jsf');
insert into curriculum.skills (skill) values ('api testing');
insert into curriculum.skills (skill) values ('ba');
insert into curriculum.skills (skill) values ('freebsd');
insert into curriculum.skills (skill) values ('jsp');
insert into curriculum.skills (skill) values ('rexx');
insert into curriculum.skills (skill) values ('bi');
insert into curriculum.skills (skill) values ('sdw');
insert into curriculum.skills (skill) values ('hadop');
insert into curriculum.skills (skill) values ('azure service bus');
insert into curriculum.skills (skill) values ('jsx');
insert into curriculum.skills (skill) values ('sed');
insert into curriculum.skills (skill) values ('selenium');
insert into curriculum.skills (skill) values ('java8');
insert into curriculum.skills (skill) values ('sem');
insert into curriculum.skills (skill) values ('typescript');
insert into curriculum.skills (skill) values ('application servers');
insert into curriculum.skills (skill) values ('seo');
insert into curriculum.skills (skill) values ('java/jee');
insert into curriculum.skills (skill) values ('midlance');
insert into curriculum.skills (skill) values ('bdd');
insert into curriculum.skills (skill) values ('rdbms');
insert into curriculum.skills (skill) values ('ci');
insert into curriculum.skills (skill) values ('adobe');
insert into curriculum.skills (skill) values ('selenium webdriver');
insert into curriculum.skills (skill) values ('firebase');
insert into curriculum.skills (skill) values ('cs');
insert into curriculum.skills (skill) values ('neo4j');
insert into curriculum.skills (skill) values ('cobol');
insert into curriculum.skills (skill) values ('db');
insert into curriculum.skills (skill) values ('resource management');
insert into curriculum.skills (skill) values ('bluecoat proxies');
insert into curriculum.skills (skill) values ('sap bi');
insert into curriculum.skills (skill) values ('visualization');
insert into curriculum.skills (skill) values ('bit bucket');
insert into curriculum.skills (skill) values ('qasymphony');
insert into curriculum.skills (skill) values ('spring core');
insert into curriculum.skills (skill) values ('ufss');
insert into curriculum.skills (skill) values ('asset management');
insert into curriculum.skills (skill) values ('stress test');
insert into curriculum.skills (skill) values ('spring data');
insert into curriculum.skills (skill) values ('sequelize');
insert into curriculum.skills (skill) values ('f5');
insert into curriculum.skills (skill) values ('ds');
insert into curriculum.skills (skill) values ('exploratory');
insert into curriculum.skills (skill) values ('10-16 hours per week');
insert into curriculum.skills (skill) values ('testrail');
insert into curriculum.skills (skill) values ('webdriver');
insert into curriculum.skills (skill) values ('vcenter');
insert into curriculum.skills (skill) values ('ca service virtualization');
insert into curriculum.skills (skill) values ('ef');
insert into curriculum.skills (skill) values ('unreal engine 4');
insert into curriculum.skills (skill) values ('it service management');
insert into curriculum.skills (skill) values ('wpf');
insert into curriculum.skills (skill) values ('csap');
insert into curriculum.skills (skill) values ('netserver');
insert into curriculum.skills (skill) values ('dc.js');
insert into curriculum.skills (skill) values ('scrum');
insert into curriculum.skills (skill) values ('maninfo');
insert into curriculum.skills (skill) values ('regression testing');
insert into curriculum.skills (skill) values ('data mining');
insert into curriculum.skills (skill) values ('jwt');
insert into curriculum.skills (skill) values ('golang');
insert into curriculum.skills (skill) values ('jws');
insert into curriculum.skills (skill) values ('oracle weblogic');
insert into curriculum.skills (skill) values ('ipma');
insert into curriculum.skills (skill) values ('bgp');
insert into curriculum.skills (skill) values ('load testing');
insert into curriculum.skills (skill) values ('hortonworks');
insert into curriculum.skills (skill) values ('csdm');
insert into curriculum.skills (skill) values ('json');
insert into curriculum.skills (skill) values ('ms 365');
insert into curriculum.skills (skill) values ('reporting');
insert into curriculum.skills (skill) values ('sit');
insert into curriculum.skills (skill) values ('appstream');
insert into curriculum.skills (skill) values ('google apis');
insert into curriculum.skills (skill) values ('sanity testing');
insert into curriculum.skills (skill) values ('redux.js');
insert into curriculum.skills (skill) values ('teradata');
insert into curriculum.skills (skill) values ('agile testing');
insert into curriculum.skills (skill) values ('go');
insert into curriculum.skills (skill) values ('packaging');
insert into curriculum.skills (skill) values ('invision');
insert into curriculum.skills (skill) values ('redmine');
insert into curriculum.skills (skill) values ('application management');
insert into curriculum.skills (skill) values ('itsm');
insert into curriculum.skills (skill) values ('bugzila');
insert into curriculum.skills (skill) values ('archimate');
insert into curriculum.skills (skill) values ('realm');
insert into curriculum.skills (skill) values ('selenium ide');
insert into curriculum.skills (skill) values ('openldap');
insert into curriculum.skills (skill) values ('hp');
insert into curriculum.skills (skill) values ('data migration');
insert into curriculum.skills (skill) values ('jasper reports');
insert into curriculum.skills (skill) values ('ibm mainframe');
insert into curriculum.skills (skill) values ('elasticsearch');
insert into curriculum.skills (skill) values ('ngenius');
insert into curriculum.skills (skill) values ('test automation engineer');
insert into curriculum.skills (skill) values ('portal');
insert into curriculum.skills (skill) values ('data wrangling');
insert into curriculum.skills (skill) values ('jpa/hibernate');
insert into curriculum.skills (skill) values ('portals');
insert into curriculum.skills (skill) values ('iq');
insert into curriculum.skills (skill) values ('sla');
insert into curriculum.skills (skill) values ('it');
insert into curriculum.skills (skill) values ('expressjs');
insert into curriculum.skills (skill) values ('sql server');
insert into curriculum.skills (skill) values ('embedded software');
insert into curriculum.skills (skill) values ('team lead');
insert into curriculum.skills (skill) values ('grafana');
insert into curriculum.skills (skill) values ('ods');
insert into curriculum.skills (skill) values ('certified aws');
insert into curriculum.skills (skill) values ('js');
insert into curriculum.skills (skill) values ('fsx');
insert into curriculum.skills (skill) values ('prince2m itil2');
insert into curriculum.skills (skill) values ('woocomerce');
insert into curriculum.skills (skill) values ('navicat');
insert into curriculum.skills (skill) values ('seaborn');
insert into curriculum.skills (skill) values ('figma');
insert into curriculum.skills (skill) values ('jenkins');
insert into curriculum.skills (skill) values ('mcitp');
insert into curriculum.skills (skill) values ('dynamo db');
insert into curriculum.skills (skill) values ('sna');
insert into curriculum.skills (skill) values ('prince 2');
insert into curriculum.skills (skill) values ('weblogic');
insert into curriculum.skills (skill) values ('retrospectives');
insert into curriculum.skills (skill) values ('acces');
insert into curriculum.skills (skill) values ('rabbitmq');
insert into curriculum.skills (skill) values ('bmc');
insert into curriculum.skills (skill) values ('black box');
insert into curriculum.skills (skill) values ('onedrive');
insert into curriculum.skills (skill) values ('system deployment');
insert into curriculum.skills (skill) values ('soa');
insert into curriculum.skills (skill) values ('ibm spss statistics');
insert into curriculum.skills (skill) values ('soc');
insert into curriculum.skills (skill) values ('conflict mechanism');
insert into curriculum.skills (skill) values ('entity-framework');
insert into curriculum.skills (skill) values ('tcp/ip');
insert into curriculum.skills (skill) values ('avaya switches');
insert into curriculum.skills (skill) values ('swagger');
insert into curriculum.skills (skill) values ('photosho[');
insert into curriculum.skills (skill) values ('conflict resolution');
insert into curriculum.skills (skill) values ('microsoft exchange');
insert into curriculum.skills (skill) values ('tdd and pair programming');
insert into curriculum.skills (skill) values ('hp test tools');
insert into curriculum.skills (skill) values ('cabling');
insert into curriculum.skills (skill) values ('helpdesk (1 year)');
insert into curriculum.skills (skill) values ('photoshop');
insert into curriculum.skills (skill) values ('jstl');
insert into curriculum.skills (skill) values ('spm');
insert into curriculum.skills (skill) values ('na');
insert into curriculum.skills (skill) values ('liferay');
insert into curriculum.skills (skill) values ('webhosting');
insert into curriculum.skills (skill) values ('gitlab');
insert into curriculum.skills (skill) values ('banyan vines');
insert into curriculum.skills (skill) values ('reseaux');
insert into curriculum.skills (skill) values ('angularjs');
insert into curriculum.skills (skill) values ('kodak');
insert into curriculum.skills (skill) values ('tailwind css');
insert into curriculum.skills (skill) values ('sqa');
insert into curriculum.skills (skill) values ('ms teams');
insert into curriculum.skills (skill) values ('nt');
insert into curriculum.skills (skill) values ('coda');
insert into curriculum.skills (skill) values ('centreon');
insert into curriculum.skills (skill) values ('pretashop');
insert into curriculum.skills (skill) values ('sql');
insert into curriculum.skills (skill) values ('dream viewer');
insert into curriculum.skills (skill) values ('pcontrol');
insert into curriculum.skills (skill) values ('backend');
insert into curriculum.skills (skill) values ('netmri');
insert into curriculum.skills (skill) values ('design thinking');
insert into curriculum.skills (skill) values ('delphi');
insert into curriculum.skills (skill) values ('oq');
insert into curriculum.skills (skill) values ('os');
insert into curriculum.skills (skill) values ('selma');
insert into curriculum.skills (skill) values ('budgeting');
insert into curriculum.skills (skill) values ('data analyst');
insert into curriculum.skills (skill) values ('hangfire');
insert into curriculum.skills (skill) values ('dell');
insert into curriculum.skills (skill) values ('srr');
insert into curriculum.skills (skill) values ('phoenix');
insert into curriculum.skills (skill) values ('2nd line support');
insert into curriculum.skills (skill) values ('functional test');
insert into curriculum.skills (skill) values ('service design');
insert into curriculum.skills (skill) values ('pq');
insert into curriculum.skills (skill) values ('ssh');
insert into curriculum.skills (skill) values ('ssm');
insert into curriculum.skills (skill) values ('ssl');
insert into curriculum.skills (skill) values ('sso');
insert into curriculum.skills (skill) values ('qa');
insert into curriculum.skills (skill) values ('lambda');
insert into curriculum.skills (skill) values ('qc');
insert into curriculum.skills (skill) values ('apache tiles');
insert into curriculum.skills (skill) values ('web development');
insert into curriculum.skills (skill) values ('toshiba');
insert into curriculum.skills (skill) values ('s3');
insert into curriculum.skills (skill) values ('selinium');
insert into curriculum.skills (skill) values ('masstransit');
insert into curriculum.skills (skill) values ('project management');
insert into curriculum.skills (skill) values ('github');
insert into curriculum.skills (skill) values ('fx / trading');
insert into curriculum.skills (skill) values ('brr');
insert into curriculum.skills (skill) values ('stl');
insert into curriculum.skills (skill) values ('autodesk maya');
insert into curriculum.skills (skill) values ('node');
insert into curriculum.skills (skill) values ('ciscio');
insert into curriculum.skills (skill) values ('rc');
insert into curriculum.skills (skill) values ('unisys');
insert into curriculum.skills (skill) values ('twilio');
insert into curriculum.skills (skill) values ('mainframe');
insert into curriculum.skills (skill) values ('app-v');
insert into curriculum.skills (skill) values ('rscs');
insert into curriculum.skills (skill) values ('nessus');
insert into curriculum.skills (skill) values ('technical support');
insert into curriculum.skills (skill) values ('design patterns');
insert into curriculum.skills (skill) values ('mpls');
insert into curriculum.skills (skill) values ('postgres');
insert into curriculum.skills (skill) values ('email');
insert into curriculum.skills (skill) values ('activemq');
insert into curriculum.skills (skill) values ('solution architect');
insert into curriculum.skills (skill) values ('ca-endevor');
insert into curriculum.skills (skill) values ('scale agile framework');
insert into curriculum.skills (skill) values ('svn');
insert into curriculum.skills (skill) values ('behaviour driven framework');
insert into curriculum.skills (skill) values ('svm');
insert into curriculum.skills (skill) values ('apache kafka');
insert into curriculum.skills (skill) values ('data center');
insert into curriculum.skills (skill) values ('elastic');
insert into curriculum.skills (skill) values ('splunk');
insert into curriculum.skills (skill) values ('testng');
insert into curriculum.skills (skill) values ('tp');
insert into curriculum.skills (skill) values ('tr');
insert into curriculum.skills (skill) values ('supermicro');
insert into curriculum.skills (skill) values ('digital ocean');
insert into curriculum.skills (skill) values ('functional programming');
insert into curriculum.skills (skill) values ('experince mostly as developer');
insert into curriculum.skills (skill) values ('express');
insert into curriculum.skills (skill) values ('webapi');
insert into curriculum.skills (skill) values ('t-sql');
insert into curriculum.skills (skill) values ('cssa');
insert into curriculum.skills (skill) values ('apache');
insert into curriculum.skills (skill) values ('ui');
insert into curriculum.skills (skill) values ('6 years it (1 data science)');
insert into curriculum.skills (skill) values ('asp.net mvc');
insert into curriculum.skills (skill) values ('oracle');
insert into curriculum.skills (skill) values ('ux');
insert into curriculum.skills (skill) values ('vb');
insert into curriculum.skills (skill) values ('looking for industry placement');
insert into curriculum.skills (skill) values ('blockchain');
insert into curriculum.skills (skill) values ('iilustrator');
insert into curriculum.skills (skill) values ('vm');
insert into curriculum.skills (skill) values ('vp');
insert into curriculum.skills (skill) values ('vr');
insert into curriculum.skills (skill) values ('support');
insert into curriculum.skills (skill) values ('css3');
insert into curriculum.skills (skill) values ('sublime');
insert into curriculum.skills (skill) values ('looking for internship');
insert into curriculum.skills (skill) values ('cocoapods');
insert into curriculum.skills (skill) values ('roi strategy');
insert into curriculum.skills (skill) values ('idea');
insert into curriculum.skills (skill) values ('realm/rxrealm');
insert into curriculum.skills (skill) values ('data warehousing');
insert into curriculum.skills (skill) values ('automated testing');
insert into curriculum.skills (skill) values ('docker');
insert into curriculum.skills (skill) values ('jira and rally');
insert into curriculum.skills (skill) values ('ruby on rails');
insert into curriculum.skills (skill) values ('data scraping');
insert into curriculum.skills (skill) values ('twitter bootstrap');
insert into curriculum.skills (skill) values ('mobile dev');
insert into curriculum.skills (skill) values ('orm');
insert into curriculum.skills (skill) values ('xd');
insert into curriculum.skills (skill) values ('statistician');
insert into curriculum.skills (skill) values ('product marketing');
insert into curriculum.skills (skill) values ('motify');
insert into curriculum.skills (skill) values ('flexbox');
insert into curriculum.skills (skill) values ('test automation');
insert into curriculum.skills (skill) values ('software');
insert into curriculum.skills (skill) values ('gbic');
insert into curriculum.skills (skill) values ('ca clarity');
insert into curriculum.skills (skill) values ('react');
insert into curriculum.skills (skill) values ('none');
insert into curriculum.skills (skill) values ('launch wizard');
insert into curriculum.skills (skill) values ('microsoft powerbi');
insert into curriculum.skills (skill) values ('sap modules: fico');
insert into curriculum.skills (skill) values ('activedirectory');
insert into curriculum.skills (skill) values ('data reconciliation');
insert into curriculum.skills (skill) values ('fredhopper');
insert into curriculum.skills (skill) values ('gcp');
insert into curriculum.skills (skill) values ('story boarding');
insert into curriculum.skills (skill) values ('teams');
insert into curriculum.skills (skill) values ('service management');
insert into curriculum.skills (skill) values ('emacs');
insert into curriculum.skills (skill) values ('insight');
insert into curriculum.skills (skill) values ('saas');
insert into curriculum.skills (skill) values ('responsive web design');
insert into curriculum.skills (skill) values ('aws solution architect');
insert into curriculum.skills (skill) values ('hive');
insert into curriculum.skills (skill) values ('adobe illustrator');
insert into curriculum.skills (skill) values ('sharepoint');
insert into curriculum.skills (skill) values ('new business development');
insert into curriculum.skills (skill) values ('springboot');
insert into curriculum.skills (skill) values ('rabbit mq');
insert into curriculum.skills (skill) values ('kms');
insert into curriculum.skills (skill) values ('dart');
insert into curriculum.skills (skill) values ('glassfish');
insert into curriculum.skills (skill) values ('virtualbox');
insert into curriculum.skills (skill) values ('tufin orchestra suite');
insert into curriculum.skills (skill) values ('test planning');
insert into curriculum.skills (skill) values ('asp.net web api 2 service');
insert into curriculum.skills (skill) values ('ci / cd');
insert into curriculum.skills (skill) values ('scrum master');
insert into curriculum.skills (skill) values ('oracle forms');
insert into curriculum.skills (skill) values ('rapidminer');
insert into curriculum.skills (skill) values ('knn');
insert into curriculum.skills (skill) values ('microsoft office suite');
insert into curriculum.skills (skill) values ('transformation');
insert into curriculum.skills (skill) values ('siteminder');
insert into curriculum.skills (skill) values ('fortinet');
insert into curriculum.skills (skill) values ('html5 games');
insert into curriculum.skills (skill) values ('statistical analysis');
insert into curriculum.skills (skill) values ('azure pipelines');
insert into curriculum.skills (skill) values ('rsjs');
insert into curriculum.skills (skill) values ('hybris pim');
insert into curriculum.skills (skill) values ('dozer');
insert into curriculum.skills (skill) values ('restful web service');
insert into curriculum.skills (skill) values ('sales');
insert into curriculum.skills (skill) values ('salesforce');
insert into curriculum.skills (skill) values ('offshoring');
insert into curriculum.skills (skill) values ('active directory');
insert into curriculum.skills (skill) values ('selenium web driver');
insert into curriculum.skills (skill) values ('flume');
insert into curriculum.skills (skill) values ('sage');
insert into curriculum.skills (skill) values ('web api');
insert into curriculum.skills (skill) values ('saga');
insert into curriculum.skills (skill) values ('matlab');
insert into curriculum.skills (skill) values ('development');
insert into curriculum.skills (skill) values ('software development');
insert into curriculum.skills (skill) values ('angular js');
insert into curriculum.skills (skill) values ('filenet');
insert into curriculum.skills (skill) values ('malware detection');
insert into curriculum.skills (skill) values ('gherkin/cucumber');
insert into curriculum.skills (skill) values ('defect loggin');
insert into curriculum.skills (skill) values ('pytho');
insert into curriculum.skills (skill) values ('pycharm');
insert into curriculum.skills (skill) values ('.net core');
insert into curriculum.skills (skill) values ('terraform');
insert into curriculum.skills (skill) values ('ios dev');
insert into curriculum.skills (skill) values ('linc');
insert into curriculum.skills (skill) values ('data management');
insert into curriculum.skills (skill) values ('scala');
insert into curriculum.skills (skill) values ('mybatis');
insert into curriculum.skills (skill) values ('cad');
insert into curriculum.skills (skill) values ('security');
insert into curriculum.skills (skill) values ('git');
insert into curriculum.skills (skill) values ('sunfire');
insert into curriculum.skills (skill) values ('servers');
insert into curriculum.skills (skill) values ('remote support');
insert into curriculum.skills (skill) values ('data visualisation');
insert into curriculum.skills (skill) values ('flex');
insert into curriculum.skills (skill) values ('testenium');
insert into curriculum.skills (skill) values ('cloud services');
insert into curriculum.skills (skill) values ('smoke');
insert into curriculum.skills (skill) values ('neoload');
insert into curriculum.skills (skill) values ('netlify');
insert into curriculum.skills (skill) values ('tableau');
insert into curriculum.skills (skill) values ('subversion');
insert into curriculum.skills (skill) values ('tdd');
insert into curriculum.skills (skill) values ('appdynamics');
insert into curriculum.skills (skill) values ('compliance');
insert into curriculum.skills (skill) values ('rest apis');
insert into curriculum.skills (skill) values ('virtual box');
insert into curriculum.skills (skill) values ('sahi');
insert into curriculum.skills (skill) values ('delegation');
insert into curriculum.skills (skill) values ('trackwise');




